stages:
  - validate

validate_docker_compose:
  stage: validate
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose -f infra/docker/reverse-proxy/compose.yaml config
    - docker compose -f infra/monitoring/compose.yaml config

validate_yaml:
  stage: validate
  image: python:3.13-alpine
  before_script:
    - pip install yamllint
  script:
    - yamllint .

validate_ansible:
  stage: validate
  image: cytopia/ansible:latest
  script:
    - ansible-playbook infra/ansible/playbooks/bootstrap.yml --syntax-check
