services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    ports:
      - "8080:80"
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    restart: unless-stopped
